version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/remove_files.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/apache_install.sh
      timeout: 300
      runas: root
